- url: http://pdp.lazada.sg/sg_uat-02-91580737.html
  delivery:
    standard:
      fee: 7.77

#- url: http://pdp.lazada.sg/dasani-drinking-water-12-x-15l-12461060.html
#  delivery:
#    standard:
#      fee: 7.77

#- url: http://pdp.lazada.sg/test-product-ha3-not-sample-80687994.html
#  delivery:
#    standard:
#      fee: 7.77

- url: http://pdp.lazada.sg/acer-xz350cu-35-ultrawide-fhd-curved-with-144hz-refresh-rate-gaming-monitor-66909057.html
  delivery:
    standard:
      fee: 7.77

- url: http://pdp.lazada.sg/acer-xz350cu-3534-ultrawide-fhd-curved-with-144hz-refresh-rate-gaming-monitor-66909057.html
  delivery:
    standard:
      fee: 7.77

- url: http://pdp.lazada.sg/intellectual-puzzle-wooden-jigsaw-puzzle-44363830.html
  delivery:
    economy:
      fee: 7.88
      promo: 'Free for products shipped from overseas'

- url: http://pdp.lazada.sg/simple-nylon-shoulder-messenger-briefcase-bag-business-bag-29681076.html
  delivery:
    economy:
      fee: 3.99
      promo: 'Free for min order of 20.00 from this Seller'

## Marketplace
- url: http://pdp.lazada.sg/beyerdynamic-mxp-50-ie-in-ear-earphone-with-mic-remote-18157808.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/sk-ii-men-moisturising-cleanser-120g-1812477.html
  delivery:
    standard:
      fee: 2.99

## Taobao
- url: http://pdp.lazada.sg/iphone77-plus-drop-resistant-apple-hard-case-fastened-ring-15234251.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/womens-hong-kong-style-retro-shopping-bag-26342736.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/couple-shoes-2017-new-style-korean-style-fashion-wild-casual-shoes-hong-kong-style-breathable-running-shoes-street-shooting-sports-shoes-female-summer-black-53367117.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/womens-korean-style-short-sleeve-t-shirt-5130-white-58321389.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/backstage-female-male-backpack-29429807.html
  delivery:
    standard:
      fee: 2.99

## Cross Border
- url: http://pdp.lazada.sg/sk-ii-whitening-spots-specialist-concentrate-05g-x-7pcs-sample-intl-15121739.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/bluetooth-wireless-in-ear-earbuds-headphones-heavy-bass-noise-isolating-hifi-earphones-white-intl-56619463.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/hdmi-high-speed-hd-14v-cable-black-for-lcd-dvd-hdtv-1m-intl-11506334.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/rj45-cat6-ethernet-network-flat-lan-cable-utp-patch-router-cables-1000m-white-1meter-intl-12947744.html
  delivery:
    standard:
      fee: 2.99

- url: http://pdp.lazada.sg/aramis-lab-series-multi-action-face-wash-100ml34oz-703425.html
  delivery:
    standard:
      fee: 2.99

## FBL 

## Retail